### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by utkudenis** [caseyryan/flutter_instagram_storyboard#4]
Hi case, 

I want to add your amazing package to my new project, 

However, you didn't update your package for 13 months, 

Dou you still continue this package?

Thank you

**Comment by caseyryan** [comment]
Hi! Thanks,
I'm not actively supporting this project at the moment but it's because I'm not using in my current projects. It's not abandoned though, I'll return to it as soon as I need it (hopefully in  2-3 months). If you have any troubles because of the outdated version of something or you have some suggestion on its API improvement, feel free to open an issue
